name: deploy-on-azure

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
           
      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test
  deploy-dev:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: 'Dev'
      url: developmentservicemwo.azurewebsites.net
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: sorting-algorithms-dev
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'DevelopmentServiceMWO'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV}}
  deploy-prod:
      runs-on: ubuntu-latest
      needs: publish
      environment:
        name: 'Prod'
        url: productionservicemwo.azurewebsites.net
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v2.1.1
          with:
            name: sorting-algorithms-prod
        - name: Azure WebApp
          uses: Azure/webapps-deploy@v3.0.0
          with:
            app-name: 'productionServiceMWO'
            publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD}}
            
