name: deploy-on-azure

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Create Version File
        run: |
          FILE_PATH=./version.txt
  
          if [ ! -f $FILE_PATH ]; then
            echo "0.0.0" > $FILE_PATH
          fi
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.create_version.outputs.version }}
          release_name: Release ${{ steps.create_version.outputs.version }}
          body: |
            Changelog and release notes go here.
  
      - name: Upload Version File
        uses: actions/upload-artifact@v2
        with:
          name: version-file
          path: version.txt
          
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
           
      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: sorting-algorithms
          path: .
          
  deploy-dev:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: Dev
      url: developmentservicemwo.azurewebsites.net
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: sorting-algorithms
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'DevelopmentServiceMWO'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV}}
  deploy-prod:
      runs-on: ubuntu-latest
      needs: publish
      environment:
        name: Prod
        url: productionservicemwo.azurewebsites.net
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v2.1.1
          with:
            name: sorting-algorithms
        - name: Azure WebApp
          uses: Azure/webapps-deploy@v3.0.0
          with:
            app-name: 'productionServiceMWO'
            publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD}}
            
